# Type  Name                  ID   GECOS                            Home                          Shell
u       security-automation   -    "Security Automation daemon"     /var/lib/security-automation-go  /usr/sbin/nologin
g       security-automation   -    "Security Automation group"      -                             -
