# Type Path                                             Mode  User                 Group                Age  Argument
d      /etc/security-automation-go                      0755  root                 root                 -    -
d      /var/lib/security-automation-go                  0750  security-automation  security-automation  -    -
d      /var/lib/security-automation-go/runtime          0750  security-automation  security-automation  -    -
d      /var/log/security-automation-go                  0755  security-automation  security-automation  -    -
