# Type Path                                           Mode  User                 Group                Age  Argument
d      /var/lib/security-automation-go               0750  security-automation  security-automation  -    -
d      /var/lib/security-automation-go/diagnostics   0750  security-automation  security-automation  -    -
d      /etc/security-automation-go/secrets           0700  security-automation  security-automation  -    -
d      /var/log/security-automation                  0755  security-automation  security-automation  -    -
